### ISSUE TITLE
[FEAT] support for displaying multi-byte characters

### ISSUE THREAD

**Issue by xiwangly2** [linuxserver/docker-firefox#34]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to request the addition of support for displaying multi-byte characters in the `linuxserver/docker-firefox` Docker image.

### Reason for change

The absence of support for multi-byte characters in the current version of the Docker image impacts the ability to properly render text in various languages. This limitation adversely affects user experience and undermines the functional integrity of the image, particularly when interacting with applications and web pages containing non-Latin characters. By introducing support for multi-byte characters, this Docker image would become more versatile and capable of handling a broader range of language content. This enhancement would cater to users across diverse linguistic backgrounds and ultimately contribute to a more inclusive and effective experience.

**Comment by thelamer** [comment]
There is a mod for this: 
https://github.com/linuxserver/docker-mods/tree/universal-internationalization

The fonts are huge and more than double the size of this container which is why we do not include them by default, please do not close this issue. I also have code I need to port over for ingesting the langpacks for firefox as they have their own extensions for the UI. https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/firefox/install_firefox.sh#L56-L68

**Comment by thelamer** [comment]
I have added the xpi language ingestion and loading to the internationalization mod, unfortunately with the Alpine version of firefox does not have autmated ingestion of the LC_ALL environment variable so it doesn't render in that language off the bat, but it does have them available in the language dropdown from settings.
